# Generated by Django 5.1.1 on 2024-10-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=2)),
                ('population', models.IntegerField()),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='cities_city_name_a4d1d7_idx'), models.Index(fields=['country_code'], name='cities_city_country_459c4a_idx')],
            },
        ),
    ]
